name: Test app with security scans

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package -DskipTests

      - name: Run SpotBugs
        run: mvn com.github.spotbugs:spotbugs-maven-plugin:spotbugs

      - name: Show SpotBugs results
        if: always()
        run: |
          echo "=== SpotBugs Report Summary ==="
          if [ -f target/spotbugsXml.xml ]; then
            grep -A 5 "<BugInstance" target/spotbugsXml.xml || echo "No bugs found."
          else
            echo "SpotBugs report not found!"
          fi

      - name: Upload SpotBugs report
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-report
          path: target/spotbugsXml.xml

      - name: Run OWASP Dependency-Check
        run: mvn org.owasp:dependency-check-maven:check

      - name: Show Dependency-Check summary
        if: always()
        run: |
          echo "=== Dependency-Check Summary ==="
          if [ -f target/dependency-check-report.html ]; then
            grep -E "Critical|High|Medium|Low" target/dependency-check-report.html || echo "No vulnerabilities found."
          else
            echo "Dependency-Check report not found!"
          fi

      - name: Upload Dependency-Check report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html
